name: Send Verification Email

on:
  workflow_dispatch:
    inputs:
      to_email:
        description: 'Email получателя'
        required: true
      token:
        description: 'Код подтверждения'
        required: true

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail via SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Код авторизации на платформе
          to: ${{ github.event.inputs.to_email }}
          from: Marketplace Support
          body: |
            Здравствуйте!

            Ваш код подтверждения для входа на маркетплейс:
            ${{ github.event.inputs.token }}
