name: Send Verification Email

on:
  repository_dispatch:
    types: [send_verification]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail via SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Код авторизации на платформе
          to: ${{ github.event.client_payload.to_email }}
          from: Marketplace Support
          body: |
            Здравствуйте!

            Ваш код подтверждения для входа на сайт:
            ${{ github.event.client_payload.token }}
